---
# Install Go Ethereum

- name: install yum dependencies
  yum:
    name:
      - gcc
      - make
    state: latest
  become: yes

- name: Download and unpack Go
  unarchive:
    src: https://dl.google.com/go/go{{ go_version }}.linux-amd64.tar.gz
    dest: /usr/local
    remote_src: yes
    creates: /usr/local/go
  become: yes

- name: create ethereum go directory
  file: path=/home/deploy/.go/src/github.com/ethereum state=directory owner=deploy group=deploy recurse=yes
  become: yes

- command: git clone https://github.com/ethereum/go-ethereum --depth 1
  args:
    chdir: /home/deploy/.go/src/github.com/ethereum
    creates: /home/deploy/.go/src/github.com/ethereum/go-ethereum
  become: yes
  become_user: deploy

- name: create node_keys
  file: path=/home/deploy/{{ wrkchain_data_dir }}/node_keys state=directory owner=deploy group=deploy recurse=yes
  become: yes
  become_user: deploy

...
